### PR TITLE
Play with instance holder

### PR DESCRIPTION
**Pull request by Denisss025**
I've played a little more with InstanceHolder. And here's the solution I've get.

Pros of the solution:
* Since there is no need in `detail::make_instance_holder()` function and `detail::get()` function, it is easier to use InstanceHolder directly.
* Since there appears default constructor, it is easier to create new instances in the `instance_cont`.
* Less memory allocations. The previous solution allocated memory twice: first for `unique_ptr` and than for `shared_ptr`. Now we do not allocate additional memory for `shared_ptr`. And the size of InstanceHolder equals to the size of  `std::shared_ptr`.

Cons of the solution:
* InstanceHolder becomes more complex.
* More lines of code needed.

### CODE REVIEW

**Comment by gracicot** [comment]
it would not be better if we work with shared_ptr<void> instead of char array? We would not be forced to store the deleter because the shared_ptr will do it for us, and it simplify the code by a lot.

**Comment by gracicot** [comment]
I got a working example of a container using void shared_ptr here: https://gist.github.com/gracicot/b413a26849fadf3d4d36

**Comment by Denisss025** [comment]
Somewhy it didn't work for me. The compiler told me that I cannot cast shared_ptr<void> to other.
I'll try once more. Maybe I've made a typo and the compiler had told me about the typo and not about casting.

**Comment by Denisss025** [comment]
Seems to be that it really was a typo and I thought I cannot use `static_pointer_cast` with void.

We don't need InstanceHolder in this case. We can use `std::shared_ptr<void>` instead. See the last commit.

**Comment by gracicot** [comment]
seems good, I'll merge this one!

**Pull request merged**
